### PR TITLE
Don't use .Rprofile, explain packrat in README

### PR DESCRIPTION
**Pull request by nacnudus**
The `packrat` bootstrap is clever and useful -- but it's surprising when the console starts installing stuff automatically.  It would seem better to point out `packrat` in the `README` to people who would look for it.

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
I'll have to have a think about this one.

On the one hand, I agree that it may come as a surprise when `packrat` starts installing stuff if not expected.

On the other hand, this is a package specifically designed for government, and the exact versions shipped in packrat/src were aligned with what was possible to install at DfE when I was there, which had a relatively restrictive IT at the time. Ultimately, the package _needs_ to be developed in the environment in which it is shipped to guarantee that it will work in the environment it is intended for. 

That said, things have probably moved on a bit since then, and I could not guarantee that the versions used in packrat/src are still correct. Also, I no longer work at DfE, and DfE is just one of many departments that have restrictive IT. 

Probably does need a warning in the README though.

**Comment by nacnudus** [comment]
There doesn't seem to be any other discussion about this, so perhaps I'm alone in being surprised.  Other languages don't have this convention though.  Up to you of course.

**Comment by ivyleavedtoadflax** [comment]
I guess in python you would just ship it with a `requirements.txt` file and expect people to construct their own environment. I don't think that there is such an expectation in R.

I think probably this does need some documentation in the README, but it seems to be standard practice to ship the .Rprofile with packrat projects, so I'm inclined to leave it.

**Comment by nacnudus** [comment]
Fair enough, I'll close this :)

**Pull request closed without merging**
