### PR TITLE
Add LICENCE file for GPL-3 (fixes #21)

### LINKED ISSUE #21: Licence
Consider adding a LICENSE file. (MIT is suitable for most GDS code, but it's more complicated if the repo contains code copied from elsewhere.)

Flagging with @DJHeron @mammykins

### PR DESCRIPTION
**Pull request by nacnudus**
See discussion #21

### CODE REVIEW

**Comment by nacnudus** [comment]
@mammykins I finally fixed the build.  Please could you review?

**Comment by mammykins** [comment]
:shipit:

**Comment by mammykins** [comment]
why was build failing?

**Comment by nacnudus** [comment]
Whichever Github API account Travis was using kept running out of requests.  It uses mine now.

**Comment by nacnudus** [comment]
@ivyleavedtoadflax I've tagged you as a reviewer because I suspect you're the only one with write access.  @mammykins' approval doesn't seem to have counted.

**Pull request merged**
