### PR TITLE
Create scale_gov function

### PR DESCRIPTION
**Pull request by mattkerlogue**
Simple function to automatically add the `gov_cols` palette to a chart.

### CODE REVIEW

**Comment by nacnudus** [comment]
@mattkerlogue yes, if you don't mind waiting a bit and switching the tests. There's a bit of a hold up while we sort out team members because we've run out of space to add @matt-dray to approve my PR.

Alternatively I could review this now and fix the visual tests later.  The AppVeyor build fail isn't anything to do with this PR, and it's fixed in mine.

**Comment by nacnudus** [comment]
Hi @mattkerlogue sorry about the horrendous wait while we figured out merge permissions.  

This branch will need translating to vdiffr.  I don't mind doing that myself, since I'm the one that broke your PR by killing visualTest, but I'm not likely to get around to it for a fortnight.

**Comment by mattkerlogue** [comment]
@nacnudus well that was a fun learning experience about git rebase. anyways, tests are now updated to vdiffr

**Review by nacnudus — APPROVED** [review]

**Comment by nacnudus** [comment]
I can't get the tests to run at the moment so I'm going to trust @mattkerlogue and merge anyway.

**Pull request merged**
